component_depth: 4
default_excludes: true
languages:
  - name: typescript
      production:
        include:
          - .*/**/.*\.vue
      test:
        include:
          - .*/**/.*\.vue
  - name: javascript
  - name: script
