export const SET_THEME = 'SET_THEME';
export const SET_THEME_COLOR = 'SET_THEME_COLOR';

export const SET_AUDIO_TRACKS = 'SET_AUDIO_TRACKS';
export const SET_VIDEO_TRACKS = 'SET_VIDEO_TRACKS';
export const SET_MV_TRACKS = 'SET_MV_TRACKS';
